import { GetServerSideProps } from "next";
import Head from "next/head";
import TabContainer from "../components/TabContainer";
import { resetServerContext } from "react-beautiful-dnd";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TabContainer />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  resetServerContext();
  return { props: { data: [] } };
};
